AIRTABLE_LANGUAGES_TABLE_SECTION = "airtable_languages_table"
AIRTABLE_EXTERNAL_RESOURCES_TABLE_SECTION = "airtable_external_resources_table"
LOGGING_SECTION = "logging"
SITES_SECTION = "sites"
SPIDERS_SECTION = "spiders"
TRANSLATED_SITE_SELECTORS_SECTION = "translated_site_selectors"
TRANSLATED_SITE_URLS_SECTION = "translated_site_urls"

PAGE_SIZE_KEY = "page_size"
MAX_RECORDS_KEY = "max_records"
LOG_FILE_KEY = "log_file"
LOG_FILE_APPEND_KEY = "log_file_append"
LOG_LEVEL_KEY = "log_level"
