RECORDS = 'records'
FIELDS = 'fields'
TITLE_FIELD = 'Title'
URL_FIELD = 'Coverage [Web: Link]'
LINK_TEXT_FIELD = 'Coverage [Web: Text]'
ISO_FIELD = 'Subject [ISO Code]'
LANGUAGE_FIELD = 'Subject [Language]'
SPIDER_FIELD = 'Spider'
